"""Fetch the 3D emoji pack used by White Screen videos and thumbnails.

Microsoft Fluent Emoji (MIT licence, github.com/microsoft/fluentui-emoji): glossy 3D, the same look
as the channel's character. Each one is saved as assets/whitescreen/emoji/<name>.webp (256 px,
transparent) and listed in index.json with the words it fits, so scripts and thumbnails can find
"the thing that goes with this word".

  python tools/ws_fetch_emoji.py          # fetches what's missing
"""
import io
import json
import sys
import urllib.parse
import urllib.request
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "whitescreen" / "emoji"
RAW = "https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/"
HANDS = {"Thumbs up", "Thumbs down", "Clapping hands", "Folded hands", "Raising hands", "Waving hand",
         "Backhand index pointing down", "Backhand index pointing left", "Backhand index pointing right",
         "Backhand index pointing up", "Index pointing at the viewer", "Index pointing up", "Flexed biceps",
         "Crossed fingers", "Heart hands", "Ok hand", "Victory hand", "Raised hand", "Raised fist",
         "Oncoming fist", "Open hands", "Palms up together", "Writing hand", "Selfie", "Pinching hand",
         "Hand with fingers splayed", "Love-you gesture", "Call me hand", "Ninja", "Detective",
         "Person shrugging", "Person facepalming", "Person raising hand", "Person gesturing no",
         "Person bowing", "Person running", "Mechanic"}

# name in the Fluent pack -> words it goes with (the first word is the asset's short name)
PACK = {
    # likes, comments, YouTube-ish
    "Thumbs up": "like likes liked thumbs up good yes",
    "Thumbs down": "dislike dislikes thumbs down bad no",
    "Speech balloon": "comment comments chat talk reply",
    "Left speech bubble": "reply replies message",
    "Thought balloon": "think thought idea wonder",
    "Right anger bubble": "rant argue mad",
    "Eye in speech bubble": "witness seen",
    "Bell": "bell notification notifications subscribe alert",
    "Bell with slash": "muted unsubscribe silent",
    "Play button": "play video watch start",
    "Pause button": "pause stop wait",
    "Stop button": "stop end",
    "Record button": "record live recording",
    "Fast-forward button": "skip forward fast",
    "Reverse button": "rewind back",
    "Repeat button": "repeat again loop replay",
    "Television": "tv television screen",
    "Movie camera": "camera filming film",
    "Video camera": "vlog recording",
    "Clapper board": "scene take action",
    "Film frames": "film movie",
    "Mobile phone": "phone screen app",
    "Mobile phone with arrow": "download share",
    "Mobile phone off": "offline",
    "Vibration mode": "buzz vibrate",
    "Laptop": "laptop computer",
    "Desktop computer": "computer pc",
    "Computer mouse": "click mouse",
    "Keyboard": "type typing keyboard",
    "Studio microphone": "mic microphone voice podcast",
    "Microphone": "sing singer karaoke",
    "Loudspeaker": "announce announcement",
    "Megaphone": "shout loud yell",
    "Speaker high volume": "sound loud volume",
    "Muted speaker": "mute quiet",
    "Headphone": "listen headphones music",
    "Antenna bars": "signal",
    "Wireless": "wifi internet online",
    "Satellite antenna": "broadcast",
    "Battery": "battery charged energy",
    "Low battery": "tired drained empty",
    "Electric plug": "plug unplug",
    "Light bulb": "idea smart tip",
    "Hundred points": "hundred perfect 100",
    "Keycap 0": "zero 0 none nobody",
    "Keycap 1": "one 1 first",
    "Keycap 2": "two 2 second",
    "Keycap 3": "three 3",
    "Keycap 10": "ten 10",
    "Keycap hashtag": "number hashtag",
    "Input numbers": "numbers count",
    "Bar chart": "stats chart views",
    "Chart increasing": "growing up rising views growth",
    "Chart decreasing": "falling down dropping",
    "Link": "link",
    "Pushpin": "pin pinned",
    "Round pushpin": "location place",
    "Paperclip": "attach",
    "Bookmark": "save saved",
    "Label": "tag label",
    "Memo": "note notes list write",
    "Clipboard": "checklist plan",
    "Page facing up": "page document",
    "Scroll": "story history old",
    "Newspaper": "news",
    "E-mail": "email mail",
    "Envelope": "letter message",
    "Love letter": "lovenote letter love",
    "Incoming envelope": "inbox",
    "Package": "box package delivery",
    "Wrapped gift": "gift surprise present",
    "Inbox tray": "inbox",
    "Outbox tray": "outbox send",
    "File folder": "folder files",
    "Card file box": "archive",
    "Wastebasket": "delete deleted trash bin remove removed",
    "Litter in bin sign": "throw away",
    "Locked": "private locked lock hidden secret",
    "Unlocked": "unlock unlocked open public",
    "Locked with key": "secure",
    "Key": "key access",
    "Old key": "unlock secret",
    "Shield": "safe protect",
    "Magnifying glass tilted left": "search find look",
    "Magnifying glass tilted right": "investigate",
    "Eye": "eye watching",
    "Eyes": "see look watching views viewers",
    "Mirror": "mirror reflection",
    "Crystal ball": "future predict prediction fortune",
    "Magic wand": "magic wish",
    "Sparkles": "sparkle new shiny special",
    "Sparkle": "spark",
    "Glowing star": "star shine",
    "Star": "favorite star rating",
    "Shooting star": "wish dream",
    "Dizzy": "dizzy",
    "Collision": "boom crash impact",
    "Fire": "fire hot lit viral trending",
    "Heart on fire": "passion",
    "High voltage": "electric energy fast quick",
    "Bomb": "bomb explode",
    "Firecracker": "firework",
    "Fireworks": "fireworks celebrate",
    "Party popper": "party congrats celebrate celebration",
    "Confetti ball": "confetti win",
    "Balloon": "balloon birthday",
    "Birthday cake": "birthday cake",
    "Trophy": "trophy win winner champion record",
    "1st place medal": "first winner gold",
    "2nd place medal": "second silver",
    "3rd place medal": "third bronze",
    "Sports medal": "medal",
    "Military medal": "honor",
    "Rosette": "award",
    "Crown": "king queen best top crown",
    "Gem stone": "rare diamond precious",
    "Ring": "ring promise",
    "Bullseye": "goal target aim",
    "Game die": "random luck chance dice",
    "Slot machine": "jackpot lucky",
    "Four leaf clover": "luck lucky",
    "Joker": "joke prank",
    "Puzzle piece": "puzzle mystery",
    "Video game": "game gaming gamer",
    "Joystick": "arcade",
    "Rocket": "launch rocket boost",
    "Flying saucer": "ufo alien",
    "Alien": "alien",
    "Robot": "robot ai algorithm bot",
    "Ghost": "ghost gone vanished deleted haunted",
    "Skull": "dead dying rip",
    "Coffin": "dead died gone",
    "Headstone": "rip grave",
    "Jack-o-lantern": "halloween pumpkin spooky",
    "Spider web": "spooky creepy",
    "Hourglass done": "time over ended",
    "Hourglass not done": "time hourglass waiting timer",
    "Alarm clock": "alarm clock deadline wake",
    "Stopwatch": "seconds timer stopwatch",
    "Timer clock": "timer countdown",
    "Watch": "watch time",
    "Mantelpiece clock": "clock hour",
    "Calendar": "date calendar day",
    "Spiral calendar": "schedule",
    "Tear-off calendar": "tomorrow today",
    "Twelve oclock": "midnight noon",
    "Warning": "warning careful danger",
    "Stop sign": "stop",
    "No entry": "no forbidden banned",
    "Prohibited": "banned blocked not allowed",
    "Police car light": "emergency alert siren",
    "Construction": "construction building",
    "Cross mark": "wrong cross no x",
    "Check mark button": "yes done correct check",
    "Check box with check": "done checked",
    "Red question mark": "question why what",
    "White question mark": "unknown",
    "Red exclamation mark": "important attention",
    "Double exclamation mark": "urgent",
    "Exclamation question mark": "what really",
    "Sos button": "help sos",
    "New button": "new",
    "Free button": "free",
    "Up! button": "up level",
    "Cool button": "cool",
    "Ok button": "ok okay",
    "Vs button": "versus vs battle",
    "Soon arrow": "soon",
    "End arrow": "end",
    "On! arrow": "on",
    "Top arrow": "top",
    "Back arrow": "back return",
    "Up arrow": "up",
    "Down arrow": "down below",
    "Right arrow": "right next",
    "Left arrow": "left",
    "Recycling symbol": "again recycle reuse",
    "Infinity": "forever infinite",
    "Atom symbol": "science",
    "Dna": "dna",
    "Brain": "brain smart iq genius",
    "Anatomical heart": "real heart",
    "Red heart": "heart love loved",
    "Sparkling heart": "cute",
    "Beating heart": "heartbeat",
    "Growing heart": "more love",
    "Two hearts": "hearts",
    "Revolving hearts": "lovely",
    "Heart with arrow": "crush",
    "Heart with ribbon": "gift love",
    "Broken heart": "broken heartbroken sad",
    "Mending heart": "healing",
    "Black heart": "dark",
    "Blue heart": "blue",
    "Purple heart": "purple",
    "Yellow heart": "yellow friend",
    "Green heart": "green",
    "Orange heart": "orange",
    "White heart": "pure",
    "Kiss mark": "kiss",
    "Anger symbol": "angry mad",
    "Sweat droplets": "sweat nervous",
    "Droplet": "drop tear",
    "Dashing away": "fast run away gone",
    "Zzz": "sleep sleeping bored zzz",
    "Bubbles": "bubbles",
    "Cyclone": "chaos crazy",
    "Tornado": "storm",
    "Cloud with lightning": "thunder",
    "Rainbow": "rainbow",
    "Sun": "sun day morning",
    "Crescent moon": "night moon",
    "Snowflake": "winter snow cold",
    "Fallen leaf": "autumn fall",
    "Christmas tree": "christmas",
    "Snowman": "snowman",
    "Globe showing americas": "world everyone global",
    "World map": "map countries",
    "Earth": "",
    "Footprints": "footsteps steps",
    "Door": "door leave exit",
    "Hole": "hole disappear",
    "Chains": "locked chained",
    "Broken chain": "free freed",
    "Hammer": "build fix",
    "Wrench": "fix repair settings",
    "Gear": "settings setup",
    "Toolbox": "tools",
    "Magnet": "attract",
    "Balance scale": "fair judge",
    "Pill": "medicine",
    "Thermometer": "fever temperature",
    "Test tube": "experiment test",
    "Microscope": "research",
    "Telescope": "look far",
    "Compass": "direction",
    "Books": "books study learn",
    "Graduation cap": "school graduate",
    "Pencil": "pencil write",
    "Crayon": "draw",
    "Artist palette": "art paint",
    "Camera with flash": "photo picture",
    "Framed picture": "picture frame",
    "Popcorn": "popcorn drama watching",
    "Pizza": "pizza food",
    "Hamburger": "burger hungry",
    "French fries": "fries",
    "Doughnut": "donut",
    "Cookie": "cookie",
    "Ice cream": "icecream",
    "Hot beverage": "coffee morning",
    "Bubble tea": "drink",
    "Teddy bear": "cute soft",
    "Cat face": "cat",
    "Dog face": "dog",
    "Unicorn": "unicorn rare",
    "Dragon": "dragon legendary",
    "T-rex": "dinosaur",
    "Penguin": "penguin",
    "Monkey face": "monkey",
    "See-no-evil monkey": "dont look embarrassing oops",
    "Hear-no-evil monkey": "dont listen",
    "Speak-no-evil monkey": "secret quiet",
    "Pile of poo": "poop",
    "Clown face": "clown fool",
    "Alien monster": "monster",
    "Goblin": "goblin",
    "Ogre": "ogre",
    "Moai": "stone stare",
    "Smiling face with sunglasses": "cool smart",
    "Face with tears of joy": "laugh lol funny",
    "Rolling on the floor laughing": "rofl hilarious",
    "Loudly crying face": "cry crying sobbing",
    "Crying face": "sad",
    "Smiling face with tear": "bittersweet",
    "Face holding back tears": "touched emotional",
    "Pleading face": "please pleading beg",
    "Face screaming in fear": "scream scared terrified",
    "Fearful face": "afraid",
    "Exploding head": "mind blown",
    "Thinking face": "thinking hmm",
    "Face with monocle": "suspicious inspect",
    "Face with raised eyebrow": "sus doubt",
    "Shushing face": "shh shush quiet",
    "Zipper-mouth face": "secret silent",
    "Face with hand over mouth": "oops",
    "Face with open eyes and hand over mouth": "gasp",
    "Face with peeking eye": "peek",
    "Melting face": "melting awkward",
    "Grimacing face": "awkward cringe",
    "Upside-down face": "silly",
    "Zany face": "crazy",
    "Star-struck": "amazing wow starstruck",
    "Smiling face with heart-eyes": "love it",
    "Smiling face with hearts": "loved",
    "Partying face": "partying",
    "Nerd face": "nerd",
    "Cowboy hat face": "yeehaw",
    "Disguised face": "disguise undercover",
    "Smirking face": "smirk",
    "Unamused face": "unamused",
    "Face with rolling eyes": "eyeroll",
    "Expressionless face": "blank",
    "Neutral face": "meh",
    "Face without mouth": "speechless",
    "Dotted line face": "invisible hidden",
    "Sleeping face": "asleep",
    "Yawning face": "boring yawn",
    "Woozy face": "dizzy confused",
    "Face with spiral eyes": "hypnotized",
    "Astonished face": "shocked astonished",
    "Hushed face": "surprised",
    "Flushed face": "embarrassed",
    "Angry face": "angry",
    "Pouting face": "furious",
    "Face with steam from nose": "frustrated",
    "Smiling face with horns": "evil devil mischief",
    "Smiling face with halo": "angel innocent",
    "Hot face": "hot",
    "Cold face": "freezing",
    "Saluting face": "salute respect",
    "Shaking face": "shaking",
    "Winking face": "wink",
    "Grinning face with sweat": "phew",
    "Anxious face with sweat": "anxious",
    "Lying face": "lie liar",
    "Money-mouth face": "",
    # hands and people
    "Clapping hands": "clap applause",
    "Folded hands": "pray thank thanks",
    "Raising hands": "yay hooray",
    "Waving hand": "hello hi bye wave",
    "Backhand index pointing down": "below down here",
    "Backhand index pointing left": "point left",
    "Backhand index pointing right": "point right",
    "Backhand index pointing up": "above up",
    "Index pointing at the viewer": "you",
    "Index pointing up": "one wait",
    "Flexed biceps": "strong strength",
    "Crossed fingers": "hope hoping",
    "Heart hands": "support",
    "Ok hand": "okay perfect",
    "Victory hand": "peace victory",
    "Raised hand": "raise hand",
    "Raised fist": "fight",
    "Oncoming fist": "punch",
    "Open hands": "hug",
    "Palms up together": "please",
    "Writing hand": "write writing",
    "Selfie": "selfie",
    "Pinching hand": "tiny little small",
    "Ninja": "ninja stealth",
    "Detective": "detective investigate",
    "Person shrugging": "shrug whatever",
    "Person facepalming": "facepalm",
    "Person raising hand": "me",
    "Person gesturing no": "nope",
    "Person running": "run running",
}


def slug(name):
    return name.lower().replace(" ", "_").replace("-", "_").replace("!", "").replace("'", "")


def url(name):
    base = name.lower().replace(" ", "_")
    if name in HANDS:
        return RAW + urllib.parse.quote(f"{name}/Default/3D/{base}_3d_default.png")
    return RAW + urllib.parse.quote(f"{name}/3D/{base}_3d.png")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    index = {}
    for name, words in PACK.items():
        if not words:
            continue
        s = slug(name)
        dst = OUT / f"{s}.webp"
        if not dst.exists():
            try:
                with urllib.request.urlopen(url(name), timeout=60) as r:
                    im = Image.open(io.BytesIO(r.read())).convert("RGBA")
                im.save(dst, lossless=True, method=6)
            except Exception as e:
                print(f"  ! {name}: {e}")
                continue
        index[s] = [w for w in words.split() if w]
    (OUT / "index.json").write_text(json.dumps(index, indent=1))
    (OUT / "LICENSE.txt").write_text("Fluent Emoji by Microsoft Corporation, MIT License.\n"
                                     "https://github.com/microsoft/fluentui-emoji/blob/main/LICENSE\n")
    print(f"{len(index)} emoji in {OUT}")


if __name__ == "__main__":
    sys.exit(main())
